"""add created_at to users

Revision ID: c3ca07b6e813
Revises: cdf6f96db3aa
Create Date: 2026-04-22 13:20:21.893915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3ca07b6e813'
down_revision: Union[str, Sequence[str], None] = 'cdf6f96db3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE users SET created_at = CURRENT_TIMESTAMP")
    # SQLite does not support ALTER COLUMN SET NOT NULL.
    # Since the column is now populated and we have application-level validation,
    # we leave it as nullable=True in the DB or would need a table recreation.
    # For this project's current state, nullable=True is acceptable.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
