"""add professional working hours table

Revision ID: f813cbcd5002
Revises: 46946aaf1792
Create Date: 2026-04-25 03:39:32.218274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f813cbcd5002'
down_revision: Union[str, Sequence[str], None] = '46946aaf1792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_working_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_working_hours_id'), 'professional_working_hours', ['id'], unique=False)
    # Removed op.alter_column for 'users.created_at' because SQLite does not support ALTER COLUMN
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed op.alter_column for 'users.created_at'
    op.drop_index(op.f('ix_professional_working_hours_id'), table_name='professional_working_hours')
    op.drop_table('professional_working_hours')
    # ### end Alembic commands ###
